name: CI
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
          include:
            - apiLevel: 33
              emuTag: google_apis
              arch: x86_64
            # - apiLevel: 30
            #   emuTag: google_apis
            #   arch: x86
            # - apiLevel: 28
            #   emuTag: default
            #   arch: x86
            - apiLevel: 23
              emuTag: default
              arch: x86

    env:
      CI: true
      ANDROID_AVD: emulator
      APPIUM_TEST_SERVER_PORT: 4567
      APPIUM_TEST_SERVER_HOST: 127.0.0.1
      FORCE_LOGS: 1
      TEST_PASS_THRESHOLD: 10

  # build:
    runs-on: ubuntu-latest
    steps:
        - name: ⬇️ Checkout Code
          uses: actions/checkout@v4

        - name: 🐢 Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: 18

        - name: 🏗️ Install WDIO
          run: npm i webdriverio

        - name: 🏗️ Install dev dependencies
          uses: actions/setup-java@v4
          with:
                distribution: 'temurin'
                java-version: '17'
        - name: Enable KVM group perms
          run: |
                echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
                sudo udevadm control --reload-rules
                sudo udevadm trigger --name-match=kvm
        - name: Setup Android SDK
          uses: android-actions/setup-android@v3
        - name: AVD cache
          uses: actions/cache@v3
          id: avd-cache
          with:
                path: |
                  ~/.android/avd/*
                  ~/.android/adb*
                key: avd-${{ matrix.apiLevel }}
        - name: create AVD and run Tests
          if: steps.avd-cache.outputs.cache-hit != 'true'
          uses: reactivecircus/android-emulator-runner@v2
          with:
                  avd-name: ${{ env.ANDROID_AVD }}
                  force-avd-creation: false
                  api-level: ${{ matrix.apiLevel }}
                  disable-spellchecker: true
                  target: ${{ matrix.emuTag }}
                  emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
                  arch: ${{ matrix.arch }}
                  disable-animations: true
                  script: npm run android.app
        - name: Publish Test Report
          uses: ./
          with:
                    report-path: './ctrf/*.json'
                    summary-report: true
                    github-report: true
                    failed-report: true
                    flaky-report: true
                    insights-report: true
                    fail-rate-report: true
                    flaky-rate-report: true
                    slowest-report: true
                    previous-results-report: true
                    use-suite-name: true
                    upload-artifact: true

        - name: 📦 Upload Logs
          uses: actions/upload-artifact@v4
          if: failure()
          with:
            name: logs
            path: logs