name: Functional Android App Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
  pull_request_target:

env:
  ANDROID_ARCH: x86
  ANDROID_TARGET: google_apis_playstore
  API_LEVEL: 30
  ANDROID_BUILD_TOOLS_VERSION: 30.0.3
  ANDROID_SDK_PACKAGES: system-images;android-30;google_apis_playstore;x86 platforms;android-30 build-tools;30.0.3 platform-tools emulator
  EMULATOR_TIMEOUT: 350
  EMULATOR_NAME: nexus
  
jobs:

  emulator-create:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          
        - name: Add avdmanager and sdkmanager to system PATH
          run: |
              echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/${{ env.ANDROID_BUILD_TOOLS_VERSION }}" >> $GITHUB_PATH
  
        - name: Install Sdk
          run: |
             yes Y | sdkmanager --licenses
             sdkmanager --install ${ANDROID_SDK_PACKAGES}
             
    
        - name: Build emulator
          run: |
              echo "no" | avdmanager --verbose create avd --force -n $EMULATOR_NAME --abi "${ANDROID_TARGET}/${ANDROID_ARCH}" -k "system-images;android-${API_LEVEL};${ANDROID_TARGET};${ANDROID_ARCH}"
  
        - name: Launch emulator
          run: |
            
           
            sudo chgrp kvm /dev/kvm
            sudo chgrp kvm /etc/group
            ls -l /dev/kvm
            ls -l /etc/group
            cat /etc/group|grep $USER
            lsmod | grep kvm
            groups
            emulator -list-avds

            chmod +x .github/workflows/start_emu_headless.sh
            EMULATOR_TIMEOUT=$EMULATOR_TIMEOUT EMULATOR_NAME=$EMULATOR_NAME .github/workflows/start_emu_headless.sh
            adb kill-server
            adb start-server
 
  android-app:
    runs-on: ubuntu-latest
    # Src: https://hugo.alliau.me/posts/2021-05-04-migration-to-github-native-dependabot-solutions-for-auto-merge-and-action-secrets.html#share-your-secrets-with-dependabot
    # If the PR is coming from a fork (pull_request_target), ensure it's opened by "dependabot[bot]".
    # Otherwise, clone it normally.
    if: |
        github.event_name == 'pull_request' ||
        (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]')
    steps:
      - name: ⬇️ Checkout Repository
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: actions/checkout@v4

      - name: ⬇️ Checkout PR Repository
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v4
        with:
            ref: ${{ github.event.pull_request.head.sha }}

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version-file: '.nvmrc'

      - name: 🧩 Install Dependencies
        run: |
          npm ci

      - name: Check for excluded dependencies
        id: check-deps
        if: github.actor == 'dependabot[bot]'
        run: |
            if echo "${{ github.event.pull_request.title }}" | grep -Eq "appium|appium-uiautomator2-driver|appium-xcuitest-driver"; then
              echo "Skipping tests due to dependency update"
              echo "::set-output name=skip::true"
            fi

      - name: 📦 Download app
        if: steps.check-deps.outputs.skip != 'true'
        run: |
            mkdir -p apps
            wget https://github.com/webdriverio/native-demo-app/releases/download/v1.0.8/android.wdio.native.app.v1.0.8.apk -P apps
                  

    # Not needed now we are running on Sauce Labs
    #   - name: 💾 Save server output
    #     if: failure()
    #     uses: actions/upload-artifact@v4
    #     with:
    #         name: android-runner-output
    #         path: |
    #             logs/
